# Generated by Django 2.2.7 on 2019-11-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='count',
            new_name='cart_count',
        ),
    ]
